services:

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173"
    working_dir: /var/www
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: desafio_database
      POSTGRES_USER: desafio_user
      POSTGRES_PASSWORD: desafio_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 
